---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  selector:
    matchLabels:
      app: producer
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: app
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: '-Xmx100m'
        - name: SPRING_PROFILES_ACTIVE
          value: 'producer'
        - name: KAFKA_BOOTSTRAPADDRESS
          value: 'kafka:9092'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: app
        imagePullPolicy: Never
        resources:
          limits:
            cpu: '300m'
        env:
        - name: JAVA_OPTS
          value: '-Xmx100m'
        - name: SPRING_PROFILES_ACTIVE
          value: 'worker'
        - name: KAFKA_BOOTSTRAPADDRESS
          value: 'kafka:9092'
---
apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
  - port: 8080
    targetPort: 8080

